apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 2
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: unchainet-demo-website:0.1.0
        name: web
        ports:
        - containerPort: 3000
          name: http-server